### ISSUE TITLE
DNNConnect.CKE (DNN 8.0.4) not allowing CKEditor plugins to install

### ISSUE THREAD

**Issue by denisjoconnor** [DNN-Connect/CKEditorProvider#73]
I have CKEditor v4.5.3 installed and have ability to create a new custom toolbar but whenever I try to reinstall the ckeditor folder (with a new configuration consisting of additional plugins) it doesn't recognise it and my rich text editor won't display at all. I have also tried to manually install the plugins with the existing CKEditor that ships with DNN 8.0.4 but again there seems to be crossover bugs in this as well. Anyone experienced this before or know of a solution or work around. Cheers

**Comment by valadas** [comment]
I also can't... Even just activating the QRcode button that is provided does not work.

**Comment by minimomo** [comment]
I successfully installed the html5video plugin with the following steps:

1. Extract the plugin zip and copy the folder to dnn CKEditor Plugins folder (..\Providers\HtmlEditorProviders\DNNConnect.CKE\js\ckeditor\4.5.3\plugins)

2. Because html5video plugin has dependencies (widget,widgetselection,clipboard,lineutils) , so need to download those plugins and copy them to dnn CKEditor Plugins folder as well.

3. Open HTML Editor Manger, at Edit config tab, add html5video to ExtraPlugins field.

4. Copy the icon file html5video.png from the plugin folder to ..\Providers\HtmlEditorProviders\DNNConnect.CKE\js\ckeditor\4.5.3\icons

5. Modify the ..\Portals\0\CKToolbarButtons.xml, add 
`<ToolbarButton>
    <ToolbarName>Html5video</ToolbarName>
    <ToolbarIcon>html5video.png</ToolbarIcon>
  </ToolbarButton>`
*please note, the first letter of the name must be capitalized, so it should be Html5video not html5video, it took me hours to find out why it didn't work

6. Now, you can find the new icon at Custom Toolbars tab of the HTML Editor Manger, then add the button to where you want.

Hope this article can help anyone. Cheers.

**Comment by valadas** [comment]
Thanks @minimomo , this helped a lot. I submitted a pull request for this plugin to be included in the next release, we'll see.
#84

**Comment by BarryAbrams** [comment]
I'm having this same issue with the image2 module. As soon as I add image2 to the extraplugins field, the editor won't load. Any help would be appreciated. I've never installed a CKEditor plugin before.

**Comment by valadas** [comment]
Moving this issue to https://github.com/dnnsoftware/Dnn.Platform/issues/4100 as we are moving this project the the Platform repository.
