### ISSUE TITLE
When modifying source, changes are lost

### ISSUE THREAD

**Issue by ohine** [DNN-Connect/CKEditorProvider#9]
Switch into source mode, modify the html and save changes BEFORE switching back to view mode in the editor. Changes are lost.

**Comment by valadas** [comment]
This appears to depend on the content, some times it is with some classes on some elements, I remember it was discussed on other issues but forgot the details and also there is a linked commit to this. If this issue is still relevant, we are merging this project into the Platform repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096, so please open a new issue there with some more details on a example where it get's stripped and should not. Thanks.
